# Generated by Django 3.2.23 on 2024-04-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_default.png', upload_to='users/profile/', verbose_name='프로필 이미지'),
        ),
    ]
