# Generated by Django 3.2.23 on 2024-04-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short_description',
        ),
    ]
