version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    build: ./nginx
    volumes:
      # - static_volume:/home/app/web/staticfiles_first
      # - media_volume:/home/app/web/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - 80:80
    depends_on:
      - web
   # restart: always
  web:
    container_name: my_web
    build:
      context: ./pastagram
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8100
    # volumes:
    #   - static_volume:/home/app/web/staticfiles_first
    #   - media_volume:/home/app/web/media

    expose:
      - 8100
    env_file:
      - ./.env.prod
    depends_on:
      - db
   # restart: always
  db:
    container_name: my_db
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    ports:
      - "5432:5432"
   # restart: always
volumes:
  postgres_data:
  static_volume:
  media_volume: