# Generated by Django 4.2.5 on 2024-01-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_image_url_postimage_url_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='url_field',
            new_name='image_url',
        ),
    ]
