# Generated by Django 4.2.5 on 2024-01-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_url_field_postimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='photo',
            field=models.ImageField(upload_to='post/PostImage_photo', verbose_name='사진'),
        ),
    ]
