# Generated by Django 4.2.5 on 2024-01-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postimage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='photo',
            field=models.ImageField(upload_to='post', verbose_name='사진'),
        ),
    ]
